### PR TITLE
Pure SQL decision tree

### PR DESCRIPTION
**Pull request by fvanderbiest**
@arnaud-morvan made the decision tree to happen within the database.
This runs much faster and is more elegant.

### CODE REVIEW

**Comment by pgiraud** [comment]
LGTM. Please merge.

**Comment by fvanderbiest** [comment]
Still working on it, sorry.

**Comment by fvanderbiest** [comment]
I did not find an easy way to merge the sources in a unique way during upscaling.

A custom window function such as 

``` sql
CREATE OR REPLACE FUNCTION join_source(text, text) RETURNS text
  AS 'SELECT $1 || $2;'
  LANGUAGE SQL IMMUTABLE STRICT;

CREATE AGGREGATE join_sources ( text ) (
  SFUNC = join_source,
  STYPE = text,
  INITCOND = ''
);
```

is not smart enough to prevent duplicates.

Leaving this as an open question.

**Comment by fvanderbiest** [comment]
Please review.

**Comment by pgiraud** [comment]
Please merge.

**Pull request merged**
